FROM node:alpine

WORKDIR /app

COPY ./package.json ./

RUN npm install --legacy-peer-deps

RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

COPY . .

CMD ["npm" , "start"]

EXPOSE 3000